# Generated by Django 6.0.3 on 2026-03-11 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_li",
                    models.CharField(
                        choices=[
                            ("xavier", "Xavier"),
                            ("sylus", "Sylus"),
                            ("zayne", "Zayne"),
                            ("rafayel", "Rafayel"),
                            ("caleb", "Caleb"),
                        ],
                        max_length=20,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Miembro"),
                            ("moderator", "Moderador"),
                            ("editor", "Editor"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("can_edit_profile", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
