# Generated by Django 6.0.3 on 2026-03-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_is_exclusive_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
